name: Github actions for integration

on: 
  push:
    branches:
      - develop
      - master
    
jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
         node-version: "14.x"
      - name: Install dependencies
        run: npm ci
      - name: Lint the project
        run: npm run lint
      - name: Crush images
        uses: crush-pics/crush-pics-github-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-key: ${{ secrets.CRUSH_API_KEY }}
      - name: Run unit tests
        run: npm run test:unit
      - name: Build the project
        run: npm run build
      - name: Run integration tests
        uses: cypress-io/github-action@v2.9.7
        with:
          command: npm run test:e2e

      
      
